In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\Datasets\Sentiment dataset\train.csv",encoding='Latin1')

In [4]:
df

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,negative,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,negative,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,noon,60-70,Angola,32866272,1246700.0,26
...,...,...,...,...,...,...,...,...,...,...
27476,4eac33d1c0,wish we could come see u on Denver husband l...,d lost,negative,night,31-45,Ghana,31072940,227540.0,137
27477,4f4c4fc327,I`ve wondered about rake to. The client has ...,", don`t force",negative,morning,46-60,Greece,10423054,128900.0,81
27478,f67aae2310,Yay good for both of you. Enjoy the break - y...,Yay good for both of you.,positive,noon,60-70,Grenada,112523,340.0,331
27479,ed167662a5,But it was worth it ****.,But it was worth it ****.,positive,night,70-100,Guatemala,17915568,107160.0,167
27480,6f7127d9d7,All this flirting going on - The ATG smiles...,All this flirting going on - The ATG smiles. Y...,neutral,morning,0-20,Guinea,13132795,246000.0,53

In [5]:
df= df[['text','sentiment']]

In [6]:
df

                                                    text sentiment
0                    I`d have responded, if I were going   neutral
1          Sooo SAD I will miss you here in San Diego!!!  negative
2                              my boss is bullying me...  negative
3                         what interview! leave me alone  negative
4       Sons of ****, why couldn`t they put them on t...  negative
...                                                  ...       ...
27476   wish we could come see u on Denver  husband l...  negative
27477   I`ve wondered about rake to.  The client has ...  negative
27478   Yay good for both of you. Enjoy the break - y...  positive
27479                         But it was worth it  ****.  positive
27480     All this flirting going on - The ATG smiles...   neutral

[27481 rows x 2 columns]

In [7]:
# data cleaning

In [8]:
df.isnull().sum()

text         1
sentiment    0
dtype: int64

In [9]:
df.dropna(inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_13752\1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [10]:
import numpy as np

In [11]:
np.array(df.sample(n=50))

array([[' No way. What about Sydney?  yeah, you guys are like the semi-older version of Short Stack. However, with the same talent.',
        'neutral'],
       ['i think iv hurt my tooth  and eilish and cassie are having a drawing competiton to draw cookies and pineapples haha :L .',
        'neutral'],
       [' thats another sponsor', 'neutral'],
       [' THIS WEBSITE GAVE ME A VIRUS! When i opened it more windows kept POPPING up',
        'negative'],
       ['success! another paper demolished! the rock god lives on! 2 more...well, 1.5 to go. Yes!!! out to celebrate awesomeness ...',
        'positive'],
       ['_UK I`ll hopefully get a chance to play it tomorrow. Hope it`s good otherwise I`ve wasted so many points',
        'positive'],
       [' what don`t be sad?  Be glad. Your 21', 'neutral'],
       ['playing machines in actinggg', 'neutral'],
       ['I`m sending a Happy Mama`s Day shout to the greatest Twit-mama ever to ... U kick ****, all day - everyday! Lovely sons!!',
        'positive'],
       ['G`morning Twitter World   A relaxing family Sunday methinks',
        'positive'],
       ['I`ve got to catch the bus to work', 'neutral'],
       [' so you should. You`re a fantastic actor it`s about time you got some recognition for it.',
        'positive'],
       ['MY best `thing` on the planet', 'positive'],
       [' Lets leave the nervousness until tomorrow!', 'neutral'],
       [' *hugs* love you, MamaBear!  Happy Mom`s Day!!!! (in case I don`t see you around tomorrow)',
        'positive'],
       [' Around better..  How are you ?', 'positive'],
       ['Entering twitter `lurk` mode, time to lock the keyboard, just poured me a whiskey',
        'neutral'],
       ['Oh snap!  Just broke my windshield while replacing my wiper blades.',
        'negative'],
       ['But I have cause I missed a lot of classes', 'negative'],
       ['_Brody What is BF ? Is it a glue ?', 'neutral'],
       ['About to Lock In on getting better  staying +', 'neutral'],
       ['With My Boy Still  He`s everything to me', 'neutral'],
       ['Leaving minneapolis, doing some homework and going to watch my brothers tennis match later',
        'neutral'],
       ['@ Ember with Dante... I have so much fun with him  can I smile any harder...',
        'positive'],
       ['Wow slept in with no dolidh here to wake me up', 'neutral'],
       ['Gossip Fluffodile here. The latest? Mad night with Teg, Jack, Lou, Tess and Frey. Had a gender war. But I was v. sad for a friend also',
        'negative'],
       [' So long as they hold your wine without tipping.', 'neutral'],
       ['Hulu Desktop looks nice but not for my region', 'positive'],
       ['Relaxing with my daughter watching Friends', 'positive'],
       ['watching Please Twins.  gonna make some Iced Tea :-bd',
        'neutral'],
       ['Doing a mass cleanout of my room before rearranging it. Just sent mother out to buy me a bin and a bookshelf since mine sucks. Bad mood',
        'negative'],
       ['should be coming out of hospital today', 'neutral'],
       [' look at your followers... your tweeps list will then be fully populated',
        'neutral'],
       ['ugh i wish this school year would go faster so i can move on in life',
        'neutral'],
       ['happy mommys day!', 'positive'],
       [' Your Steve Chai sounds awesome. *wishes she had one now* But I`m stuck with: Idon`tknowwhatdamnbrandcoffeethisis',
        'positive'],
       ['#3wordsaftersex I haven`t started', 'neutral'],
       [' umm..nope not anymoree', 'neutral'],
       ['is tired if ppl **** talking', 'negative'],
       [' http://twitpic.com/4w483 you guys look so nice', 'positive'],
       ['anyone drive a newish diesel car? any advice on pros cons? not interested in old diesel cars, need recent model experience, eg SUV',
        'negative'],
       [' Your missing qualifying  I think David Reutimann is leading with a 22.96 ....',
        'negative'],
       ['Happy imma get to see some lovely ladies', 'positive'],
       ['about to start work and missing him like crazy.I wont be seeing him till Tuesday',
        'negative'],
       ['i messed up my back/hip. it hurts so bad', 'negative'],
       ['i am very very tired', 'negative'],
       ['Omg i just seen the sun and the moon in the same place  this disproves my theory that they are the same person',
        'negative'],
       ['On my way to work! I`m runnin late and I`m sooooo tired!',
        'negative'],
       ['Listening 2 music @ home all alone lol  who wants 2 come over & hang with me LOL!!',
        'neutral'],
       ['14 pages left to read, then it will be time to start all over again, and again.  Off to Lunch Duty...love 6th graders',
        'positive']], dtype=object)

In [12]:

import re
import html
import pandas as pd

def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Decode HTML entities
    text = html.unescape(text)

    # Normalize backtick apostrophes
    text = text.replace("`", "'")

    # Lowercase
    text = text.lower()

    # Remove Markdown links, keeping visible text
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML tags
    text = re.sub(r'<[^>]*>', ' ', text)

    # Remove @mentions
    text = re.sub(r'@\w+', ' ', text)

    # Keep hashtag text
    text = re.sub(r'#(\w+)', r'\1', text)

    # Expand common contractions
    text = re.sub(r"\bcan't\b", "cannot", text)
    text = re.sub(r"\bwon't\b", "will not", text)
    text = re.sub(r"n't\b", " not", text)
    text = re.sub(r"'re\b", " are", text)
    text = re.sub(r"'ve\b", " have", text)
    text = re.sub(r"'ll\b", " will", text)
    text = re.sub(r"'m\b", " am", text)
    text = re.sub(r"'d\b", " would", text)

    # Handle common emoticons before removing punctuation
    text = re.sub(r'[:;=8][-^]?[)(/DPp]', ' EMOTICON ', text)
    text = re.sub(r'<3', ' LOVE ', text)

    # Remove censored words such as ****
    text = re.sub(r'\*+', ' ', text)

    # Keep only letters and whitespace
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text


# Apply to your DataFrame
df['clean_text'] = df['text'].apply(clean_text)

# Check the output
print(df[['text', 'clean_text', 'sentiment']].head(15))

                                                 text  \
0                 I`d have responded, if I were going
1       Sooo SAD I will miss you here in San Diego!!!
2                           my boss is bullying me...
3                      what interview! leave me alone
4    Sons of ****, why couldn`t they put them on t...
5   http://www.dothebouncy.com/smf - some shameles...
6   2am feedings for the baby are fun when he is a...
7                                          Soooo high
8                                         Both of you
9    Journey!? Wow... u just became cooler.  hehe....
10   as much as i love to be hopeful, i reckon the...
11  I really really like the song Love Story by Ta...
12       My Sharpie is running DANGERously low on ink
13  i want to go to music tonight but i lost my vo...
14                         test test from the LG enV2

                                           clean_text sentiment
0              i would have responded if i were going   neutral
1          sooo sad i will miss you here in san diego  negative
2                              my boss is bullying me  negative
3                       what interview leave me alone  negative
4   sons of why could not they put them on the rel...  negative
5   some shameless plugging for the best rangers f...   neutral
6   am feedings for the baby are fun when he is al...  positive
7                                          soooo high   neutral
8                                         both of you   neutral
9   journey wow u just became cooler hehe is that ...  positive
10  as much as i love to be hopeful i reckon the c...   neutral
11  i really really like the song love story by ta...  positive
12       my sharpie is running dangerously low on ink  negative
13  i want to go to music tonight but i lost my voice  negative
14                          test test from the lg env   neutral

C:\Users\HP\AppData\Local\Temp\ipykernel_13752\1999369194.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['clean_text'] = df['text'].apply(clean_text)

In [13]:
df

,text,sentiment,clean_text
0,"I`d have responded, if I were going",neutral,i would have responded if i were going
1,Sooo SAD I will miss you here in San Diego!!!,negative,sooo sad i will miss you here in san diego
2,my boss is bullying me...,negative,my boss is bullying me
3,what interview! leave me alone,negative,what interview leave me alone
4,"Sons of ****, why couldn`t they put them on t...",negative,sons of why could not they put them on the rel...
...,...,...,...
27476,wish we could come see u on Denver husband l...,negative,wish we could come see u on denver husband los...
27477,I`ve wondered about rake to. The client has ...,negative,i have wondered about rake to the client has m...
27478,Yay good for both of you. Enjoy the break - y...,positive,yay good for both of you enjoy the break you p...
27479,But it was worth it ****.,positive,but it was worth it
27480,All this flirting going on - The ATG smiles...,neutral,all this flirting going on the atg smiles yay ...

In [14]:
df.drop('text',axis=1,inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_13752\364109082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('text',axis=1,inplace=True)

In [15]:
# 1. Check missing values
print("Missing values:")
print(df[["clean_text", "sentiment"]].isna().sum())

# 2. Check empty or whitespace-only cleaned tweets
empty_mask = df["clean_text"].str.strip().eq("")

print("\nEmpty cleaned tweets:", empty_mask.sum())

# 3. Inspect empty rows and their sentiment labels
display(df.loc[empty_mask, ["clean_text", "sentiment"]])

# 4. Check the cleaned text examples
display(df[["clean_text", "sentiment"]].head(10))

Missing values:
clean_text    0
sentiment     0
dtype: int64

Empty cleaned tweets: 4

      clean_text sentiment
8120              negative
24926              neutral
25691              neutral
26005              neutral

                                          clean_text sentiment
0             i would have responded if i were going   neutral
1         sooo sad i will miss you here in san diego  negative
2                             my boss is bullying me  negative
3                      what interview leave me alone  negative
4  sons of why could not they put them on the rel...  negative
5  some shameless plugging for the best rangers f...   neutral
6  am feedings for the baby are fun when he is al...  positive
7                                         soooo high   neutral
8                                        both of you   neutral
9  journey wow u just became cooler hehe is that ...  positive

In [16]:
# Remove empty or whitespace-only cleaned tweets
df = df.loc[~empty_mask].copy()

print("Updated dataset shape:", df.shape)
print("Empty tweets remaining:",
      df["clean_text"].str.strip().eq("").sum())

print("\nSentiment distribution:")
print(df["sentiment"].value_counts())

Updated dataset shape: (27476, 2)
Empty tweets remaining: 0

Sentiment distribution:
sentiment
neutral     11114
positive     8582
negative     7780
Name: count, dtype: int64

In [17]:
# Encoding techniques
# CBOW
# TF-IDF
# WORD2VEC
# then 
# ML ALGORITHM

In [18]:
# classification
# ML algorithms

# neural network
# CBOW , TF-IDF
# EMBEDDING LAYER
# ---> RNN,LSTM

In [19]:
# import count vectorizer
# apply on text
# divide data inot train test
# different ML models 
# performance(confusion Matrix)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
from sklearn.model_selection import train_test_split

X = df['clean_text']
y = df['sentiment']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.5,stratify=y)

print('Training shape:',X_train.shape)
print('Testing shape:',X_test.shape)

Training shape: (13738,)
Testing shape: (13738,)

In [22]:
# converting into word count vectors
cv = CountVectorizer()

X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

print("Training shape:", X_train_cv.shape)
print("Testing shape:", X_test_cv.shape)

Training shape: (13738, 15687)
Testing shape: (13738, 15687)

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix)

In [24]:
# training

lr = LogisticRegression()
lr.fit(X_train_cv,y_train)

c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [25]:
y_pred_lr = lr.predict(X_test_cv)

In [26]:
print("accuracy_score:",accuracy_score(y_test,y_pred_lr))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

accuracy_score: 0.6772455961566458

Classification Report:
              precision    recall  f1-score   support

    negative       0.70      0.61      0.65      3890
     neutral       0.62      0.72      0.66      5557
    positive       0.76      0.69      0.72      4291

    accuracy                           0.68     13738
   macro avg       0.69      0.67      0.68     13738
weighted avg       0.68      0.68      0.68     13738


Confusion Matrix:
[[2370 1310  210]
 [ 854 3990  713]
 [ 185 1162 2944]]

In [27]:
# multinomial naive bayes 

from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(X_train_cv,y_train)

MultinomialNB()

In [28]:
y_pred_nb = nb.predict(X_test_cv)

In [29]:
print("Accuracy:",accuracy_score(y_test,y_pred_nb))
print("\nClassification report:",classification_report(y_test,y_pred_nb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_nb))

Accuracy: 0.6391760081525695

Classification report:               precision    recall  f1-score   support

    negative       0.68      0.54      0.60      3890
     neutral       0.57      0.70      0.63      5557
    positive       0.73      0.65      0.68      4291

    accuracy                           0.64     13738
   macro avg       0.66      0.63      0.64     13738
weighted avg       0.65      0.64      0.64     13738


Confusion Matrix:
[[2104 1588  198]
 [ 814 3908  835]
 [ 190 1332 2769]]

In [30]:
# Linear SVM 
from sklearn.svm import LinearSVC

svm = LinearSVC(random_state=42,max_iter=3000)

svm.fit(X_train_cv,y_train)

LinearSVC(max_iter=3000, random_state=42)

In [31]:
y_pred_svm = svm.predict(X_test_cv)

print("Accuracy:", accuracy_score(y_test, y_pred_svm))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Accuracy: 0.6535157956034358

Classification Report:
              precision    recall  f1-score   support

    negative       0.65      0.61      0.63      3890
     neutral       0.61      0.66      0.63      5557
    positive       0.72      0.69      0.70      4291

    accuracy                           0.65     13738
   macro avg       0.66      0.65      0.65     13738
weighted avg       0.66      0.65      0.65     13738


Confusion Matrix:
[[2357 1253  280]
 [1006 3667  884]
 [ 256 1081 2954]]

In [32]:
# knn classifier
from sklearn.decomposition import TruncatedSVD
from sklearn.neighbors import KNeighborsClassifier


svd = TruncatedSVD(n_components=100,random_state=42)

X_train_svd = svd.fit_transform(X_train_cv)
X_test_svd = svd.transform(X_test_cv)


print("Training shape:", X_train_svd.shape)
print("Testing shape:", X_test_svd.shape)

Training shape: (13738, 100)
Testing shape: (13738, 100)

In [33]:
knn = KNeighborsClassifier(n_neighbors=5,n_jobs=-1)
knn.fit(X_train_svd,y_train)

KNeighborsClassifier(n_jobs=-1)

In [34]:
y_pred_knn = knn.predict(X_test_svd)

In [35]:
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_knn))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))

Accuracy: 0.479109040617266

Classification Report:
              precision    recall  f1-score   support

    negative       0.40      0.43      0.42      3890
     neutral       0.48      0.61      0.54      5557
    positive       0.62      0.35      0.44      4291

    accuracy                           0.48     13738
   macro avg       0.50      0.46      0.47     13738
weighted avg       0.50      0.48      0.47     13738


Confusion Matrix:
[[1689 1885  316]
 [1543 3411  603]
 [ 953 1856 1482]]

In [36]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42,max_depth=100)

dt.fit(X_train_cv,y_train)

DecisionTreeClassifier(max_depth=100, random_state=42)

In [37]:
y_pred_dt = dt.predict(X_test_cv)

In [38]:
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Accuracy: 0.6388848449555976

Classification Report:
              precision    recall  f1-score   support

    negative       0.65      0.49      0.56      3890
     neutral       0.58      0.75      0.66      5557
    positive       0.73      0.64      0.68      4291

    accuracy                           0.64     13738
   macro avg       0.66      0.62      0.63     13738
weighted avg       0.65      0.64      0.64     13738


Confusion Matrix:
[[1908 1682  300]
 [ 722 4142  693]
 [ 306 1258 2727]]

In [39]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100,max_depth=30,random_state=42,n_jobs=-1)

rf.fit(X_train_cv,y_train)

RandomForestClassifier(max_depth=30, n_jobs=-1, random_state=42)

In [40]:
y_pred_rf = rf.predict(X_test_cv)

In [41]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.5941185034211676

Classification Report:
              precision    recall  f1-score   support

    negative       0.83      0.24      0.37      3890
     neutral       0.51      0.91      0.65      5557
    positive       0.83      0.51      0.63      4291

    accuracy                           0.59     13738
   macro avg       0.72      0.55      0.55     13738
weighted avg       0.70      0.59      0.56     13738


Confusion Matrix:
[[ 924 2857  109]
 [ 160 5050  347]
 [  34 2069 2188]]

In [42]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (2.2.0)
Requirement already satisfied: scipy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (1.18.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
from xgboost import XGBClassifier

In [44]:
xgb = XGBClassifier(
    objective = "multi:softprob",
    num_Class = 3,
    n_estimators = 100,
    max_depth = 6,
    learning_rate = 0.1,
    random_state = 42,
    eval_metric = "mlogloss",
    n_jobs = 1
)

In [45]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

y_train_encoded = lb.fit_transform(y_train)

y_test_encoded = lb.transform(y_test)

In [46]:
xgb.fit(X_train_cv,y_train_encoded)

c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [12:36:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:794:
Parameters: { "num_Class" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=1, num_Class=3, ...)

In [47]:
y_pred_xgb = xgb.predict(X_test_cv)

In [48]:
print("Accuracy:", accuracy_score(y_test_encoded, y_pred_xgb))

print(classification_report(
    y_test_encoded,
    y_pred_xgb,
    labels=y_test_encoded,
    target_names=lb.classes_
))

Accuracy: 0.6535885864026787
              precision    recall  f1-score   support

    negative       0.76      0.45      0.57      3890
     neutral       0.76      0.45      0.57      3890
    positive       0.57      0.83      0.68      5557

    accuracy                           0.66  64425030
   macro avg       0.69      0.65      0.65  64425030
weighted avg       0.68      0.68      0.65  64425030

c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:3106: UserWarning: labels size, 13738, does not match size of target_names, 3
  warnings.warn(

In [49]:
print("y_test type:", type(y_test))
print("y_test shape:", getattr(y_test, "shape", None))

print("y_test_encoded type:", type(y_test_encoded))
print("y_test_encoded shape:", getattr(y_test_encoded, "shape", None))

print("y_pred_xgb type:", type(y_pred_xgb))
print("y_pred_xgb shape:", getattr(y_pred_xgb, "shape", None))

print("Test labels:", len(y_test_encoded))
print("Predictions:", len(y_pred_xgb))

y_test type: <class 'pandas.core.series.Series'>
y_test shape: (13738,)
y_test_encoded type: <class 'numpy.ndarray'>
y_test_encoded shape: (13738,)
y_pred_xgb type: <class 'numpy.ndarray'>
y_pred_xgb shape: (13738,)
Test labels: 13738
Predictions: 13738

In [50]:
from sklearn.metrics import accuracy_score, classification_report

# Convert numeric predictions back to sentiment names
y_pred_labels = lb.inverse_transform(y_pred_xgb)

print("Accuracy:", accuracy_score(y_test, y_pred_labels))

print(classification_report(
    y_test,
    y_pred_labels,
    labels=["negative", "neutral", "positive"],
    digits=4
))

Accuracy: 0.6535885864026787
              precision    recall  f1-score   support

    negative     0.7582    0.4522    0.5665      3890
     neutral     0.5681    0.8319    0.6751      5557
    positive     0.7918    0.6052    0.6860      4291

    accuracy                         0.6536     13738
   macro avg     0.7060    0.6298    0.6426     13738
weighted avg     0.6918    0.6536    0.6478     13738

# Word2Vec + LSTM for Tweet Sentiment Analysis

In [51]:
print('X_train:',X_train.shape)
print('y_train:',y_train.shape)

print('X_test:',X_test.shape)
print('y_test:',y_test.shape)

X_train: (13738,)
y_train: (13738,)
X_test: (13738,)
y_test: (13738,)

In [52]:
import gensim
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string 
import nltk
import numpy as np

In [53]:
nltk.download('punkt_tab') 
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [54]:
word_tokenize(X_train.iloc[0])

['you',
 'are',
 'a',
 'very',
 'naughty',
 'woman',
 'we',
 'sooo',
 'have',
 'to',
 'meet']

In [55]:
sentences = [word_tokenize(tweet) for tweet in X_train]

print("Number of training tweets:", len(sentences))
print("First tokenized tweet:", sentences[0])

Number of training tweets: 13738
First tokenized tweet: ['you', 'are', 'a', 'very', 'naughty', 'woman', 'we', 'sooo', 'have', 'to', 'meet']

In [56]:
w2v = Word2Vec(sentences=sentences,vector_size=100,window=5,min_count=2,workers=2,sg=1,epochs=5,seed=42)

In [57]:
w2v.wv['watching']

array([ 0.20105107,  0.03175309, -0.08386679,  0.18183409,  0.089795  ,
        0.4042686 ,  0.04954296,  0.19471414, -0.07729039, -0.2865123 ,
       -0.2388671 , -0.03530018,  0.14844736,  0.15385772, -0.2788731 ,
       -0.23875928, -0.09748382, -0.09805498, -0.20577168, -0.01132496,
        0.02228357, -0.00201652,  0.0848347 ,  0.11493707,  0.1708392 ,
        0.09127633, -0.12902965,  0.05080394, -0.24503924, -0.2773054 ,
        0.04065179, -0.04304684,  0.12171821,  0.12989463,  0.01817106,
       -0.000748  ,  0.06188595, -0.19974951, -0.2810127 ,  0.05975754,
        0.08288118,  0.164867  ,  0.3674912 , -0.0666993 ,  0.02278569,
        0.16730295,  0.06310768,  0.06763563,  0.42382184, -0.16097753,
       -0.22138266, -0.47014916,  0.00123425,  0.02500215,  0.20460154,
       -0.08717673, -0.1420861 , -0.09686384, -0.00253511,  0.06239401,
       -0.09175681,  0.03042711, -0.178114  ,  0.27919874,  0.14113124,
        0.06314016,  0.07485631, -0.13859053, -0.3017994 ,  0.06529143,
       -0.18209395,  0.14501682, -0.10519451,  0.0756811 ,  0.2509444 ,
       -0.05053447,  0.00047787,  0.04576088, -0.2563094 ,  0.114742  ,
        0.2152104 , -0.2987309 , -0.11720898,  0.06109361, -0.13100274,
       -0.15426598,  0.03772942,  0.04188123,  0.08758236, -0.06246974,
       -0.18123041,  0.30529442,  0.32988137, -0.22408296,  0.22097094,
       -0.15924259, -0.11925934,  0.06854415, -0.21896482, -0.10514516],
      dtype=float32)

In [58]:
print("Vocabulary size:", len(w2v.wv))

print("\nVector for 'watching':")
print(w2v.wv["watching"])

print("\nVector shape:", w2v.wv["watching"].shape)

Vocabulary size: 6478

Vector for 'watching':
[ 0.20105107  0.03175309 -0.08386679  0.18183409  0.089795    0.4042686
  0.04954296  0.19471414 -0.07729039 -0.2865123  -0.2388671  -0.03530018
  0.14844736  0.15385772 -0.2788731  -0.23875928 -0.09748382 -0.09805498
 -0.20577168 -0.01132496  0.02228357 -0.00201652  0.0848347   0.11493707
  0.1708392   0.09127633 -0.12902965  0.05080394 -0.24503924 -0.2773054
  0.04065179 -0.04304684  0.12171821  0.12989463  0.01817106 -0.000748
  0.06188595 -0.19974951 -0.2810127   0.05975754  0.08288118  0.164867
  0.3674912  -0.0666993   0.02278569  0.16730295  0.06310768  0.06763563
  0.42382184 -0.16097753 -0.22138266 -0.47014916  0.00123425  0.02500215
  0.20460154 -0.08717673 -0.1420861  -0.09686384 -0.00253511  0.06239401
 -0.09175681  0.03042711 -0.178114    0.27919874  0.14113124  0.06314016
  0.07485631 -0.13859053 -0.3017994   0.06529143 -0.18209395  0.14501682
 -0.10519451  0.0756811   0.2509444  -0.05053447  0.00047787  0.04576088
 -0.2563094   0.114742    0.2152104  -0.2987309  -0.11720898  0.06109361
 -0.13100274 -0.15426598  0.03772942  0.04188123  0.08758236 -0.06246974
 -0.18123041  0.30529442  0.32988137 -0.22408296  0.22097094 -0.15924259
 -0.11925934  0.06854415 -0.21896482 -0.10514516]

Vector shape: (100,)

In [59]:
tweet_lengths = [len(tokens) for tokens in sentences]


print("Shortest tweet:", min(tweet_lengths))
print("Longest tweet:", max(tweet_lengths))
print("Average tweet length:", sum(tweet_lengths) / len(tweet_lengths))

print("\nLength percentiles:")
print("50th percentile:", np.percentile(tweet_lengths, 50))
print("90th percentile:", np.percentile(tweet_lengths, 90))
print("95th percentile:", np.percentile(tweet_lengths, 95))
print("99th percentile:", np.percentile(tweet_lengths, 99))

Shortest tweet: 1
Longest tweet: 35
Average tweet length: 13.113626437618285

Length percentiles:
50th percentile: 12.0
90th percentile: 23.0
95th percentile: 25.0
99th percentile: 29.0

In [60]:
max_length = 25

In [61]:
X_train_vectors = [
    [w2v.wv[word] for word in word_tokenize(tweet)
     if word in w2v.wv]
    for tweet in X_train
]

In [62]:
print("First tweet:", X_train.iloc[0])
print("Number of word vectors:", len(X_train_vectors[0]))
print("Shape of first word vector:", X_train_vectors[0][0].shape)

First tweet: you are a very naughty woman we sooo have to meet
Number of word vectors: 10
Shape of first word vector: (100,)

In [63]:
X_test_vectors = [
    [w2v.wv[word] for word in word_tokenize(tweet)
     if word in w2v.wv]
    for tweet in X_test
]

In [64]:
print("Number of test tweets:", len(X_test_vectors))
print("First test tweet:", X_test.iloc[0])
print("Number of word vectors:", len(X_test_vectors[0]))

Number of test tweets: 13738
First test tweet: about to start my least favourite chore mopping the floor
Number of word vectors: 8

In [65]:
max_length = 25
vector_size = w2v.vector_size

X_train_padded = np.zeros(
    (len(X_train_vectors), max_length, vector_size),
    dtype=np.float32
)

for i, tweet_vectors in enumerate(X_train_vectors):
    tweet_vectors = np.asarray(tweet_vectors, dtype=np.float32)
    length = min(len(tweet_vectors), max_length)

    if length > 0:
        X_train_padded[i, :length] = tweet_vectors[:length]

print("Training shape:", X_train_padded.shape)
print("Tweets with no known word vectors:", sum(len(v) == 0 for v in X_train_vectors))

Training shape: (13738, 25, 100)
Tweets with no known word vectors: 34

In [66]:
X_test_padded = np.zeros(
    (len(X_test_vectors), max_length, vector_size),
    dtype=np.float32
)

for i, tweet_vectors in enumerate(X_test_vectors):
    tweet_vectors = np.asarray(tweet_vectors, dtype=np.float32)
    length = min(len(tweet_vectors), max_length)

    if length > 0:
        X_test_padded[i, :length] = tweet_vectors[:length]

print("Training shape:", X_train_padded.shape)
print("Testing shape:", X_test_padded.shape)

Training shape: (13738, 25, 100)
Testing shape: (13738, 25, 100)

In [87]:
print("y_train_encoded:",y_train_encoded.shape)
print("y_test_encoded:",y_test_encoded.shape)

y_train_encoded: (13738,)
y_test_encoded: (13738,)

In [71]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.21.0)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: absl-py>=1.0.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\hp\appdata\roaming\python\python313\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (7.36.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.4.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.83.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.2.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [72]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Dropout,Masking

In [74]:
import tensorflow as tf

In [75]:
model_lstm = tf.keras.Sequential([tf.keras.layers.Masking(mask_value = 0.0,input_shape = (max_length,vector_size)),
                     tf.keras.layers.LSTM(64),
                     tf.keras.layers.Dense(32,activation="relu"),
                     tf.keras.layers.Dropout(0.3),
                     tf.keras.layers.Dense(3,activation='softmax')])

c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\masking.py:48: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [77]:
model_lstm.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ masking (Masking)               │ (None, 25, 100)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        42,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44,419 (173.51 KB)

 Trainable params: 44,419 (173.51 KB)

 Non-trainable params: 0 (0.00 B)

In [78]:
model_lstm.compile(loss='sparse_categorical_crossentropy',
                   optimizer = 'adam',
                   metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [80]:
history_lstm = model_lstm.fit(X_train_padded,y_train_encoded,epochs=10,batch_size=32,validation_split=0.5,verbose=1)

Epoch 1/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.6277 - loss: 0.8120 - val_accuracy: 0.6059 - val_loss: 0.8424
Epoch 2/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6330 - loss: 0.7981 - val_accuracy: 0.6056 - val_loss: 0.8546
Epoch 3/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6439 - loss: 0.7850 - val_accuracy: 0.6090 - val_loss: 0.8472
Epoch 4/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6406 - loss: 0.7803 - val_accuracy: 0.6053 - val_loss: 0.8566
Epoch 5/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6537 - loss: 0.7699 - val_accuracy: 0.6110 - val_loss: 0.8595
Epoch 6/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6499 - loss: 0.7655 - val_accuracy: 0.6010 - val_loss: 0.8511
Epoch 7/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6561 - loss: 0.7532 - val_accuracy: 0.6119 - val_loss: 0.8412
Epoch 8/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6671 - loss: 0.7436 - val_accuracy: 0.6139 - val_loss: 0.8396
Epoch 9/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6666 - loss: 0.7303 - val_accuracy: 0.6171 - val_loss: 0.8496
Epoch 10/10
215/215 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.6726 - loss: 0.7217 - val_accuracy: 0.6110 - val_loss: 0.8505

In [81]:
y_pred_probs = model_lstm.predict(X_test_padded)

y_pred_lstm = np.argmax(y_pred_probs,axis=1)

print("Predictions shape:", y_pred_lstm.shape)
print("First 10 predictions:", y_pred_lstm[:10])
print("First 10 actual labels:", y_test_encoded[:10])

430/430 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step
Predictions shape: (13738,)
First 10 predictions: [1 0 1 1 1 1 0 1 1 0]
First 10 actual labels: [0 0 1 1 1 1 0 2 0 0]

In [86]:
print("Test Accuracy:", accuracy_score(y_test_encoded, y_pred_lstm))

print("\nClassification Report:")
print(classification_report(
    y_test_encoded,
    y_pred_lstm,
    target_names=lb.classes_
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_encoded, y_pred_lstm))

Test Accuracy: 0.6187217935652933

Classification Report:
              precision    recall  f1-score   support

    negative       0.57      0.57      0.57      3890
     neutral       0.57      0.67      0.62      5557
    positive       0.77      0.59      0.67      4291

    accuracy                           0.62     13738
   macro avg       0.64      0.61      0.62     13738
weighted avg       0.63      0.62      0.62     13738


Confusion Matrix:
[[2223 1471  196]
 [1238 3736  583]
 [ 437 1313 2541]]